name: Build Catan Rule Index

# Auslöser: bei jedem Push in main und manuell über GitHub UI
on:
  push:
    branches: [rag-catan-rulebot]
  workflow_dispatch:

jobs:
  build-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run preprocessing (PDF → chunks.json)
        run: |
          python src/app/preprocess.py

      - name: Build embeddings & FAISS index
        run: |
          python src/app/indexer.py

      - name: Commit generated files
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "github-actions[bot]"
          author_email: "github-actions[bot]@users.noreply.github.com"
          message: "Auto-update chunks, metadata & FAISS index"
          add: |
            data/index/chunks.json
            data/index/metadata.json
            data/index/faiss.index
